services:
  postgres:
    image: postgres:16
    container_name: todo-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: todoappdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build:
      context: ./To-Do Application API
    container_name: todo-backend
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ConnectionStrings__DefaultConnection: "Host=postgres;Port=5432;Database=todoappdb;Username=postgres;Password=123"
      ASPNETCORE_ENVIRONMENT: Development
    ports:
      - "5051:8080"

  frontend:
    build:
      context: ./to-do-application-frontend
    container_name: todo-frontend
    depends_on:
      - backend
    ports:
      - "4200:80"

volumes:
  postgres_data:
